version: "2"
linters:
  default: none
  enable:
    - bidichk
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - gocritic
    - govet
    - ineffassign
    - misspell
    - nonamedreturns
    - prealloc
    - revive
    - staticcheck
    - unused
    - whitespace
    - wrapcheck
  settings:
    govet:
      enable-all: true
      disable:
        - shadow
  exclusions:
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy
formatters:
  enable:
    - gci
    - gofumpt
    - goimports
  settings:
    gci:
      custom-order: true
      sections:
        - standard
        - default
        - localmodule
        - blank
        - dot
